### ISSUE TITLE
How to get real time bid / ask / price from GDAX websocket feed

### ISSUE THREAD

**Issue by vdaubry** [coinbase/coinbase-exchange-ruby#27]
I’m trying to display an OHLC graph similar to the one on GDAX website

The API doc discourages polling on /ticker endpoint, and recommend to use the websocket stream to listen for match message

But the match response only provide a price and a side (sell / buy)

How can i recreate the ticker data (price, ask and bid) from the websocket feed ?

```
{
  “price”: “333.99”,
  “size”: “0.193”,
  “bid”: “333.98”,
  “ask”: “333.99”,
  “volume”: “5957.11914015”,
  “time”: “2015-11-14T20:46:03.511254Z”
}
```

The ticker endpoint and the websocket feed both return a 'price', but i guess that it's not the same. Is the price from the ticker endpoint some sort of average over time ?

How can i compute Bid value, Ask value ?

**Comment by ajmajma** [comment]
@vdaubry did you ever happen to figure this out?

**Comment by seasick** [comment]
Afaik, for a OHLC graph you wouldn't use orderbook data (bid, ask) but use ticker data (everytime a trade happens, you get a price and a size) by subscribing to the _ticker_ channel.

From there you just store the _time_, _price_ and _size_ and calculate the values for the different time frames.

e.g. with "15m" candles, the first value received between 13:00 and 13:15 will be the **open** value, the last one the **close** value. Same with highest and lowest. And the volume is just the sum over all sizes you stored in this time frame.

This worked very well for me.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
