### ISSUE TITLE
SSL errors using Client and AsyncClient

### ISSUE THREAD

**Issue by rloomba** [coinbase/coinbase-exchange-ruby#33]
similar to #17 

```ruby
rest_api = Coinbase::Exchange::Client.new("redacted")

rest_api.last_trade(product_id: "BTC-USD") do |resp|
  puts resp.price
end
```

OSX 10.13.1, ruby 2.4.4
coinbase-exchange-ruby-1a9d2a7f612f/lib/coinbase/exchange/adapters/net_http.rb#35
error: `SSL_connect returned=1 errno=0 state=error: certificate verify failed`

Does ca-coinbase.crt need to be updated?

**Comment by jesseproudman** [comment]
@rloomba Did you solve this?

**Comment by jesseproudman** [comment]
For future reference, was able to fix this by disabling the custom certificates: https://github.com/strixleviathan/coinbase-exchange-ruby/pull/2

**Comment by rloomba** [comment]
@jesseproudman yeah figured it out, it was an ssl cert config issue on the dev box.

**Comment by Skeyelab** [comment]
@rloomba - do you remember what you did to fix this?  It seems to have popped up on my server and locally.

maybe its on their end.

**Comment by rloomba** [comment]
> @rloomba - do you remember what you did to fix this? It seems to have popped up on my server and locally.
> 
> maybe its on their end.

I can't recall exactly...just be sure your SSL certs are valid.
