### ISSUE TITLE
Gdax to Coinbase Pro

### ISSUE THREAD

**Issue by mchalise** [coinbase/coinbase-exchange-ruby#35]
Are you guys going change API URL from Gdax to Coinbase Pro?

**Comment by nextpulse** [comment]
I forked and made a one line change.  Everything works 'as is' so far.

coinbase-exchange-ruby/lib/coinbase/exchange/api_client.rb
 `        @api_uri = URI.parse(options[:api_url] || "https://api.pro.coinbase.com")`

**Comment by mchalise** [comment]
Could you please send a Pull Request. Thanks.
