### ISSUE TITLE
Update documentation based on GET /fills deprecation notice 

### ISSUE THREAD

**Issue by mchalise** [coinbase/coinbase-exchange-ruby#38]
There's a giant deprecation notice for the GET /fills endpoint https://docs.gdax.com/#fills

The README on this project needs to be updated to have an example of how to pass in the product_id or order_id.

> Coinbase::Exchange::BadRequestError: {"message":"query must contained either product_id or order_id"}

I am getting this error.

**Comment by mchalise** [comment]
> GET /products  

Will provide product ids. But I am now confused on how to do pagination any idea?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
